version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
      timezone: "Etc/UTC"
    open-pull-requests-limit: 5
    rebase-strategy: auto
    commit-message:
      prefix: "chore"
      include: "scope"
    labels:
      - "dependencies"
      - "security"
  # Optionally set assignees or reviewers later (fields omitted for now to satisfy schema)
  # Optionally ignore large frameworks until explicitly upgraded
    ignore: []
