name: PR Changelog Tests

on:
  push:
    branches: [ main, 'ci/**', 'docs/**' ]
  pull_request:
    paths:
      - '.github/workflows/pr-changelog-guard.yml'
      - 'scripts/**'
      - 'test/**'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Run changelog-detect tests
        run: |
          node test/changelog-detect.test.mjs