name: PR Changelog Recheck

on:
  issue_comment:
    types: [created]

permissions:
  contents: read
  pull-requests: write
  issues: write

jobs:
  recheck:
    runs-on: ubuntu-latest
    if: >-
      startsWith(github.event.comment.body, '/recheck-changelog') && github.event.issue.pull_request != null
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Trigger PR guard workflow by re-dispatching (via workflow_dispatch)
        uses: actions/github-script@v6
        with:
          script: |
            (async () => {
              const module = await import(process.env.GITHUB_WORKSPACE + '/.github/js_repo_tools/changelog/pr-changelog-recheck.mjs');
              await module.run(github, context, core, {});
            })();
