name: PR Changelog Recheck

on:
  issue_comment:
    types: [created]

permissions:
  contents: read
  pull-requests: write
  issues: write

jobs:
  recheck:
    runs-on: ubuntu-latest
    if: >-
      startsWith(github.event.comment.body, '/recheck-changelog') && github.event.issue.pull_request != null
    steps:
      - name: Trigger PR guard workflow by re-dispatching (via workflow_dispatch)
        uses: actions/github-script@v6
        with:
          script: |
            const prNumber = github.event.issue.number;
            // Create a comment acknowledging the recheck
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: prNumber,
              body: 'Re-running PR changelog guard as requested...',
            });
            // Re-run by calling the checks API: request a re-run of the last workflow run for this PR
            const runs = await github.rest.actions.listWorkflowRunsForRepo({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'pr-changelog-guard.yml',
              per_page: 10,
            });
            if (runs.data.workflow_runs.length) {
              const lastRun = runs.data.workflow_runs[0];
              await github.rest.actions.reRunWorkflow({
                owner: context.repo.owner,
                repo: context.repo.repo,
                run_id: lastRun.id,
              });
            }